// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2px1oTvYWuK7mJJ8u7_VyTFNgWNNqxqk',
    appId: '1:829302826679:android:0d60bc4a62efffc7050f32',
    messagingSenderId: '829302826679',
    projectId: 'women-on-wheels-f8970',
    storageBucket: 'women-on-wheels-f8970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaEWd02872D1SNWQscYtv-fn_IGX0qCdI',
    appId: '1:829302826679:ios:04bf310b2de81482050f32',
    messagingSenderId: '829302826679',
    projectId: 'women-on-wheels-f8970',
    storageBucket: 'women-on-wheels-f8970.firebasestorage.app',
    iosBundleId: 'com.example.womenOnWheelsApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0YdbIDXWqg18_6fFSPo_A_gkHpgLfHHI',
    appId: '1:829302826679:web:385a595176c62f95050f32',
    messagingSenderId: '829302826679',
    projectId: 'women-on-wheels-f8970',
    authDomain: 'women-on-wheels-f8970.firebaseapp.com',
    storageBucket: 'women-on-wheels-f8970.firebasestorage.app',
    measurementId: 'G-YEB2ZBMYH4',
  );
}
